[package]
name = "ashellcore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
brush-core = { path = "../vendor/brush/brush-core" }
brush-builtins = { path = "../vendor/brush/brush-builtins" }
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1", features = ["rt", "macros", "time"] }
regex-lite = "0.1.9"
futures = { version = "0.3.33", default-features = false, features = ["std"] }
libc = "0.2.189"
brush-coreutils-builtins = { version = "0.1.0", path = "../vendor/brush/brush-coreutils-builtins", features = ["coreutils.all"] }
uucore = "0.8"
grep-searcher = "0.1"
grep-regex = "0.1"
grep-matcher = "0.1"
base64 = "0.23.0"

[profile.release]
opt-level = "s"
lto = true

[patch.crates-io]
uucore = { path = "../vendor/patches/uucore" }
uu_date = { path = "../vendor/patches/uu_date" }
uu_cp = { path = "../vendor/patches/uu_cp" }
uu_tail = { path = "../vendor/patches/uu_tail" }
uu_whoami = { path = "../vendor/patches/uu_whoami" }

[[test]]
name = "battery"
harness = false

[[test]]
name = "concurrency"
harness = false

[features]
python = []
vision = []
node = []
