[package]
name = "ashellcore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
brush-core = { path = "../vendor/brush/brush-core" }
brush-builtins = { path = "../vendor/brush/brush-builtins" }
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1", features = ["rt", "macros", "time"] }
regex-lite = "0.1.9"

[profile.release]
opt-level = "s"
lto = true
